# Generated by Django 6.1 on 2026-08-08 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('date_text', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pursuing', 'Pursuing'), ('completed', 'Completed')], default='completed', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('skills_learned', models.CharField(blank=True, help_text='Comma-separated list', max_length=400)),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('web', 'Web Application'), ('design', 'Design')], default='web', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('features', models.CharField(blank=True, help_text='Comma-separated, shown with check icons', max_length=400)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('private', 'Private')], default='completed', max_length=15)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Sanjaya Kandel', max_length=120)),
                ('tagline', models.CharField(default='Full Stack Web Developer & UI/UX Designer', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('email', models.EmailField(default='kandelsanjaya7@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('location', models.CharField(default='Nepal', max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('cv_url', models.CharField(blank=True, max_length=300)),
                ('projects_completed', models.PositiveSmallIntegerField(default=5)),
                ('years_experience', models.PositiveSmallIntegerField(default=2)),
                ('client_satisfaction', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Visitor Log',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_class', models.CharField(help_text='Font Awesome class, e.g. fab fa-python', max_length=80)),
                ('category', models.CharField(choices=[('core', 'Core Technology (progress bar)'), ('tool', 'Tool / Technology'), ('learning', 'Currently Learning')], default='tool', max_length=10)),
                ('percentage', models.PositiveSmallIntegerField(default=0, help_text='Only used for Core Technology (0-100)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
