# Generated by Django 6.1 on 2026-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your featured hero/profile photo here. Replaces the default photo on the homepage.', null=True, upload_to='profile/'),
        ),
    ]
