# Generated by Django 6.1 on 2026-08-10 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_profile_photo_to_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('cv', 'CV / Resume'), ('certificate', 'Certificate / Diploma'), ('transcript', 'Academic Transcript'), ('project', 'Project Document'), ('other', 'Other Document')], default='cv', max_length=20)),
                ('file', models.FileField(help_text='Upload your PDF, DOCX, or image document', upload_to='documents/')),
                ('description', models.TextField(blank=True, help_text='Optional document details or notes')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume PDF or document here. Takes priority over cv_url.', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cv_url',
            field=models.CharField(blank=True, help_text='External URL to your CV (if no file uploaded)', max_length=300),
        ),
    ]
