# Generated by Django 6.1 on 2026-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_sitesettings_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload optional video file for this document', null=True, upload_to='documents/videos/'),
        ),
        migrations.AddField(
            model_name='document',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or paste external video link'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload demo video (MP4/WebM) for this project', null=True, upload_to='projects/videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or paste external video link (YouTube, Vimeo, or MP4 URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload your intro/showcase video (MP4/WebM)', null=True, upload_to='profile/videos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Or paste video URL for intro showcase'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('cv', 'CV / Resume'), ('certificate', 'Certificate / Diploma'), ('transcript', 'Academic Transcript'), ('project', 'Project Document'), ('video', 'Video Showcase'), ('other', 'Other Document')], default='cv', max_length=20),
        ),
    ]
